repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: uv run --locked ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: uv run --locked ruff format
        language: system
        types: [python]
      - id: mdformat
        name: Markdown format
        entry: uv run --locked mdformat --number
        language: system
        types: [markdown]
      - id: prettier
        name: Documentation format
        entry: docs/node_modules/.bin/prettier --write --ignore-path docs/.prettierignore
        language: system
        files: ^docs/.*\.(css|json|jsonc|mjs|ts|tsx|yaml)$
      - id: console-prettier
        name: Console format
        entry: console/node_modules/.bin/prettier --write
        language: system
        files: ^console/.*\.(css|html|json|ts|tsx|yaml)$
